name: Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  deployments: write

# Allow one concurrent deployment
concurrency:
  group: "docs"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4
      - name: Generate Docs
        run: ./Scripts/Build_Doc.sh
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 692bd58c8585abc099232c16459f7af4
          command: pages deploy ./public --project-name=easyrichtext
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
